### ISSUE TITLE
Image dimensions not preserved for "Testing your own image"

### ISSUE THREAD

**Issue by sjscotti** [IsHYuhi/BEDSR-Net_A_Deep_Shadow_Removal_Network_from_a_Single_Document_Image#17]
Hi
I have started experimenting with your code in using my own images.  I find that regardless of the input image dimensions, the processed images are always  768x1024.  So they get distorted when I process them or lose resolution.  Is there a way to set the output dimensions to match the original image dimensions?
Thanks!

**Comment by IsHYuhi** [comment]
I’m sorry for the delayed response.

This code resizes all images to 512x512 for training.
Therefore, if you want to perform inference at high resolution, set the number of pixels in the Transform to a number divisible by 2^5 (but this may reduce performance since the resolution is not the same as the training resolution). 

Thanks.
